-- 코드를 입력하세요
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(PRICE*SALES) AS SALES
FROM BOOK JOIN AUTHOR USING(AUTHOR_ID) JOIN BOOK_SALES USING(BOOK_ID)
WHERE
    TO_CHAR(SALES_DATE, 'YYYY')='2022' AND
    TO_CHAR(SALES_DATE, 'MM')='01'
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;